# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 
  name: Default
  vmImage: LAPTOP-QIJC73OK

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\Users\YASWANTH\Downloads\New folder'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: 'C:\Users\YASWANTH\Downloads\New folder'
